// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public string Id { get; set; }
        public string UserId { get; set; }
        public string OrderCode { get; set; }
        public string Barcode { get; set; }
        public decimal? PayAmount { get; set; }
        public decimal? DueAmount { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Vat { get; set; }
        public decimal? ShippingAmount { get; set; }
        public decimal? ReceiveAmount { get; set; }
        public decimal? ChangeAmount { get; set; }
        public string OrderMode { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentType { get; set; }
        public DateTime? ActionDate { get; set; }
        public string ActionBy { get; set; }
        public int? BranchId { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public decimal? TotalWeight { get; set; }
        public bool? IsFrozen { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}