// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class OrderItem
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public string ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal? Discount { get; set; }
        public decimal Price { get; set; }
        public decimal? TotalPrice { get; set; }
        public string ImageUrl { get; set; }
        public DateTime ActionDate { get; set; }
        public string Title { get; set; }
        public decimal? CostPrice { get; set; }
        //public string AttributeVariationId { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}