// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class ProductImage
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string ImageName { get; set; }
        public int? DisplayOrder { get; set; }
        public bool IsPrimaryImage { get; set; }
        public bool IsApproved { get; set; }
        public DateTime? ActionDate { get; set; }

        public virtual Product Product { get; set; }
    }
}