// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class Purchase
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public int SupplierId { get; set; }
        public int? Quantity { get; set; }
        public decimal? Weight { get; set; }
        public string Unit { get; set; }
        public decimal? Tax { get; set; }
        public decimal Price { get; set; }
        public DateTime PurchaseDate { get; set; }
        public DateTime ActionDate { get; set; }

        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}