// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class SliderImage
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public int? DisplayOrder { get; set; }
        public string Url { get; set; }
    }
}