// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class StockLocation
    {
        public StockLocation()
        {
            ProductStocks = new HashSet<ProductStock>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ProductStock> ProductStocks { get; set; }
    }
}