// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Model.Models
{
    public partial class User
    {
        public User()
        {
            Orders = new HashSet<Order>();
            Products = new HashSet<Product>();
            UserRoles = new HashSet<UserRole>();
            UserBranches = new HashSet<UserBranch>();
        }

        public string Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipZipCode { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipCountry { get; set; }
        public string PhotoUrl { get; set; }
        public DateTime? LastLoginTime { get; set; }
        public DateTime CreateDate { get; set; }
        public bool? IsManual { get; set; }
        public bool IsVerified { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool? IsSync { get; set; }
        public string Code { get; set; }
        public string Permissions { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }        
        public virtual ICollection<UserBranch> UserBranches { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}